version: "3.8"
services:
  database:
    image: mariadb:10.6.16
    container_name: db
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      MARIADB_USER: ${DATABASE_USER}
      MARIADB_PASSWORD: ${DATABASE_USER_PASSWORD}
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_ROOT_PASSWORD: ${DATABASE_USER_PASSWORD}
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 10s
      retries: 45
  server:
    build: ../.
    container_name: rest-server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_HOST: db
      MODEL_SAVE_PATH: /app/models
    volumes:
      - ${MODEL_PATH}:/app/models
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "http://127.0.0.1:${SERVER_PORT}/meditations"
        ]
      interval: 2s
      timeout: 2s
      retries: 10

