name: integration-tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Deploy Docker containers
      run: |
        cd integration
        cp .env.template .env
        export INITIALIZE_DB=true
        docker compose up -d --wait
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
    - name: Run robot tests
      run: |
        ./integration_tests/run_tests.sh
    - name: Archive test log
      uses: actions/upload-artifact@v4
      with:
        name: integration-test-logs
        path: integration_tests/integration_test_results/log.html